import torch
x = torch.rand(5,3)
print("x的shape为:",x.shape)
print("x的dtype为:",x.dtype)
print("x的device为:",x.device)
y = torch.tensor([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
y = y.view(5,3)
print("x+y为:",torch.add(input=x,alpha=1,other=y))
print("x-y为:",torch.sub(input=x,alpha=1,other=y))
print("x*y为:",torch.mul(x,y))
print("x/y为:",torch.div(x,y))
y_numpy = y.numpy()
print("y转化为numpy的形式:",y_numpy)
y_tensor = torch.from_numpy(y_numpy)
print("重新转化回来的y:",y_tensor)
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = x.to(device)
    print("放在cuda上的x:",x)